export type JbhOrientation = "introverted" | "extraverted";
export type JbhFunction = "N" | "S" | "T" | "F";

export type JbhQuestion = {
  id: string;
  question: string;
  function: JbhFunction;
  orientation: JbhOrientation;
};

export const JBH_QUESTIONS: JbhQuestion[] = [
  { id: "ni-01", question: "I often sense where a situation is heading long before it becomes obvious.", function: "N", orientation: "introverted" },
  { id: "ni-02", question: "My understanding tends to crystallize into a single interpretation.", function: "N", orientation: "introverted" },
  { id: "ni-03", question: "I lose interest in ideas once they no longer fit a central vision.", function: "N", orientation: "introverted" },
  { id: "ni-04", question: "Insights feel discovered rather than constructed.", function: "N", orientation: "introverted" },
  { id: "ni-05", question: "I trust patterns that are internally coherent even without evidence.", function: "N", orientation: "introverted" },
  { id: "ni-06", question: "I find it hard to explain how I reached certain conclusions.", function: "N", orientation: "introverted" },
  { id: "ni-07", question: "I focus more on trajectory than on present details.", function: "N", orientation: "introverted" },
  { id: "ni-08", question: "I prefer depth of insight over breadth of exploration.", function: "N", orientation: "introverted" },
  { id: "ni-09", question: "Contradictory information feels disruptive unless it can be integrated.", function: "N", orientation: "introverted" },
  { id: "ni-10", question: "I seek the core meaning behind events.", function: "N", orientation: "introverted" },
  { id: "ni-11", question: "My thinking feels compressed rather than expansive.", function: "N", orientation: "introverted" },
  { id: "ni-12", question: "I become frustrated with constant brainstorming.", function: "N", orientation: "introverted" },
  { id: "ni-13", question: "I sense inevitability more than choice.", function: "N", orientation: "introverted" },
  { id: "ni-14", question: "I prefer refining an insight to generating alternatives.", function: "N", orientation: "introverted" },
  { id: "ni-15", question: "I notice themes repeating across unrelated contexts.", function: "N", orientation: "introverted" },
  { id: "ni-16", question: "I feel disoriented when there is no unifying direction.", function: "N", orientation: "introverted" },
  { id: "ne-01", question: "One idea naturally leads me to many others.", function: "N", orientation: "extraverted" },
  { id: "ne-02", question: "I enjoy exploring ideas without needing conclusions.", function: "N", orientation: "extraverted" },
  { id: "ne-03", question: "I resist narrowing options too early.", function: "N", orientation: "extraverted" },
  { id: "ne-04", question: "Connections between unrelated topics come easily.", function: "N", orientation: "extraverted" },
  { id: "ne-05", question: "I feel energized by open-ended discussion.", function: "N", orientation: "extraverted" },
  { id: "ne-06", question: "I reinterpret situations in multiple ways.", function: "N", orientation: "extraverted" },
  { id: "ne-07", question: "I enjoy reframing problems creatively.", function: "N", orientation: "extraverted" },
  { id: "ne-08", question: "I notice alternative meanings others miss.", function: "N", orientation: "extraverted" },
  { id: "ne-09", question: "I prefer flexibility over certainty.", function: "N", orientation: "extraverted" },
  { id: "ne-10", question: "I get bored refining a single idea for too long.", function: "N", orientation: "extraverted" },
  { id: "ne-11", question: "I feel constrained by fixed interpretations.", function: "N", orientation: "extraverted" },
  { id: "ne-12", question: "Ideas feel provisional rather than final.", function: "N", orientation: "extraverted" },
  { id: "ne-13", question: "I enjoy exploring what-if scenarios.", function: "N", orientation: "extraverted" },
  { id: "ne-14", question: "I’m more curious about possibilities than outcomes.", function: "N", orientation: "extraverted" },
  { id: "ne-15", question: "I generate ideas faster than I evaluate them.", function: "N", orientation: "extraverted" },
  { id: "ne-16", question: "I prefer expanding concepts over concluding them.", function: "N", orientation: "extraverted" },
  { id: "si-01", question: "I compare new experiences to what I already know.", function: "S", orientation: "introverted" },
  { id: "si-02", question: "Familiar methods feel reliable.", function: "S", orientation: "introverted" },
  { id: "si-03", question: "I notice when something deviates from what’s expected.", function: "S", orientation: "introverted" },
  { id: "si-04", question: "My understanding builds cumulatively over time.", function: "S", orientation: "introverted" },
  { id: "si-05", question: "I trust what has proven dependable before.", function: "S", orientation: "introverted" },
  { id: "si-06", question: "Sudden change feels unsettling.", function: "S", orientation: "introverted" },
  { id: "si-07", question: "Details gain meaning through personal context.", function: "S", orientation: "introverted" },
  { id: "si-08", question: "I value consistency.", function: "S", orientation: "introverted" },
  { id: "si-09", question: "I recall experiences vividly in relation to how they felt.", function: "S", orientation: "introverted" },
  { id: "si-10", question: "I prefer established procedures.", function: "S", orientation: "introverted" },
  { id: "si-11", question: "I reference past examples when deciding.", function: "S", orientation: "introverted" },
  { id: "si-12", question: "I feel grounded by routine.", function: "S", orientation: "introverted" },
  { id: "si-13", question: "I notice subtle changes from a baseline.", function: "S", orientation: "introverted" },
  { id: "si-14", question: "I rely on internal impressions of how things are.", function: "S", orientation: "introverted" },
  { id: "si-15", question: "I am cautious with untested approaches.", function: "S", orientation: "introverted" },
  { id: "si-16", question: "I prefer refinement over novelty.", function: "S", orientation: "introverted" },
  { id: "se-01", question: "I feel most aware in real-time situations.", function: "S", orientation: "extraverted" },
  { id: "se-02", question: "I notice physical details effortlessly.", function: "S", orientation: "extraverted" },
  { id: "se-03", question: "I prefer responding to what’s happening now.", function: "S", orientation: "extraverted" },
  { id: "se-04", question: "I act quickly when circumstances demand it.", function: "S", orientation: "extraverted" },
  { id: "se-05", question: "Abstract discussion feels incomplete without examples.", function: "S", orientation: "extraverted" },
  { id: "se-06", question: "I enjoy immersive sensory experiences.", function: "S", orientation: "extraverted" },
  { id: "se-07", question: "I adapt easily to changing environments.", function: "S", orientation: "extraverted" },
  { id: "se-08", question: "I trust direct observation.", function: "S", orientation: "extraverted" },
  { id: "se-09", question: "I focus on what is tangible and present.", function: "S", orientation: "extraverted" },
  { id: "se-10", question: "I notice opportunities as they arise.", function: "S", orientation: "extraverted" },
  { id: "se-11", question: "I prefer experience over speculation.", function: "S", orientation: "extraverted" },
  { id: "se-12", question: "I react instinctively in dynamic situations.", function: "S", orientation: "extraverted" },
  { id: "se-13", question: "I feel energized by physical interaction with the world.", function: "S", orientation: "extraverted" },
  { id: "se-14", question: "I dislike excessive theorizing.", function: "S", orientation: "extraverted" },
  { id: "se-15", question: "I engage with what’s immediately available.", function: "S", orientation: "extraverted" },
  { id: "se-16", question: "I prioritize actuality over potential.", function: "S", orientation: "extraverted" },
  { id: "ti-01", question: "I evaluate ideas by internal consistency.", function: "T", orientation: "introverted" },
  { id: "ti-02", question: "Logical contradictions bother me deeply.", function: "T", orientation: "introverted" },
  { id: "ti-03", question: "I refine concepts until they make exact sense.", function: "T", orientation: "introverted" },
  { id: "ti-04", question: "I distrust conclusions I don’t fully understand.", function: "T", orientation: "introverted" },
  { id: "ti-05", question: "I enjoy analyzing systems for coherence.", function: "T", orientation: "introverted" },
  { id: "ti-06", question: "I question assumptions others take for granted.", function: "T", orientation: "introverted" },
  { id: "ti-07", question: "I prefer reasoning to authority.", function: "T", orientation: "introverted" },
  { id: "ti-08", question: "I dissect problems into components.", function: "T", orientation: "introverted" },
  { id: "ti-09", question: "I value accuracy over efficiency.", function: "T", orientation: "introverted" },
  { id: "ti-10", question: "I enjoy clarifying definitions.", function: "T", orientation: "introverted" },
  { id: "ti-11", question: "I hesitate to act without conceptual clarity.", function: "T", orientation: "introverted" },
  { id: "ti-12", question: "I revise my understanding when inconsistencies appear.", function: "T", orientation: "introverted" },
  { id: "ti-13", question: "I prefer elegant explanations.", function: "T", orientation: "introverted" },
  { id: "ti-14", question: "I test ideas mentally before applying them.", function: "T", orientation: "introverted" },
  { id: "ti-15", question: "I seek truth over agreement.", function: "T", orientation: "introverted" },
  { id: "ti-16", question: "I feel uneasy with vague reasoning.", function: "T", orientation: "introverted" },
  { id: "te-01", question: "I focus on what produces results.", function: "T", orientation: "extraverted" },
  { id: "te-02", question: "I prefer clear goals and plans.", function: "T", orientation: "extraverted" },
  { id: "te-03", question: "I trust objective criteria.", function: "T", orientation: "extraverted" },
  { id: "te-04", question: "I organize tasks to improve efficiency.", function: "T", orientation: "extraverted" },
  { id: "te-05", question: "I value measurable outcomes.", function: "T", orientation: "extraverted" },
  { id: "te-06", question: "I become impatient with unproductive discussion.", function: "T", orientation: "extraverted" },
  { id: "te-07", question: "I prefer action to prolonged analysis.", function: "T", orientation: "extraverted" },
  { id: "te-08", question: "I optimize systems for performance.", function: "T", orientation: "extraverted" },
  { id: "te-09", question: "I rely on standards and benchmarks.", function: "T", orientation: "extraverted" },
  { id: "te-10", question: "I feel compelled to implement decisions.", function: "T", orientation: "extraverted" },
  { id: "te-11", question: "I prioritize effectiveness over elegance.", function: "T", orientation: "extraverted" },
  { id: "te-12", question: "I manage resources strategically.", function: "T", orientation: "extraverted" },
  { id: "te-13", question: "I expect follow-through.", function: "T", orientation: "extraverted" },
  { id: "te-14", question: "I structure environments to support goals.", function: "T", orientation: "extraverted" },
  { id: "te-15", question: "I focus on what works in practice.", function: "T", orientation: "extraverted" },
  { id: "te-16", question: "I assess success externally.", function: "T", orientation: "extraverted" },
  { id: "fi-01", question: "I evaluate situations by personal values.", function: "F", orientation: "introverted" },
  { id: "fi-02", question: "I feel my values deeply and privately.", function: "F", orientation: "introverted" },
  { id: "fi-03", question: "Authenticity matters more than consensus.", function: "F", orientation: "introverted" },
  { id: "fi-04", question: "Emotional reactions feel informative.", function: "F", orientation: "introverted" },
  { id: "fi-05", question: "I resist compromising core beliefs.", function: "F", orientation: "introverted" },
  { id: "fi-06", question: "I trust my inner sense of right and wrong.", function: "F", orientation: "introverted" },
  { id: "fi-07", question: "I experience values as individual, not negotiated.", function: "F", orientation: "introverted" },
  { id: "fi-08", question: "I feel discomfort when acting against my beliefs.", function: "F", orientation: "introverted" },
  { id: "fi-09", question: "I protect personal ideals strongly.", function: "F", orientation: "introverted" },
  { id: "fi-10", question: "I prefer sincerity over harmony.", function: "F", orientation: "introverted" },
  { id: "fi-11", question: "My values feel intrinsic rather than chosen.", function: "F", orientation: "introverted" },
  { id: "fi-12", question: "I reflect on how situations align with who I am.", function: "F", orientation: "introverted" },
  { id: "fi-13", question: "I dislike being pressured to justify values.", function: "F", orientation: "introverted" },
  { id: "fi-14", question: "Emotional integrity matters deeply to me.", function: "F", orientation: "introverted" },
  { id: "fi-15", question: "I evaluate meaning personally.", function: "F", orientation: "introverted" },
  { id: "fi-16", question: "I feel guided by inner conviction.", function: "F", orientation: "introverted" },
  { id: "fe-01", question: "I adjust expression based on others’ emotions.", function: "F", orientation: "extraverted" },
  { id: "fe-02", question: "I sense emotional atmospheres in groups.", function: "F", orientation: "extraverted" },
  { id: "fe-03", question: "I prioritize relational harmony.", function: "F", orientation: "extraverted" },
  { id: "fe-04", question: "I consider how actions affect others.", function: "F", orientation: "extraverted" },
  { id: "fe-05", question: "I feel responsible for group morale.", function: "F", orientation: "extraverted" },
  { id: "fe-06", question: "I notice unspoken social expectations.", function: "F", orientation: "extraverted" },
  { id: "fe-07", question: "I adapt to maintain connection.", function: "F", orientation: "extraverted" },
  { id: "fe-08", question: "I value shared understanding.", function: "F", orientation: "extraverted" },
  { id: "fe-09", question: "I feel discomfort when emotional needs are unmet.", function: "F", orientation: "extraverted" },
  { id: "fe-10", question: "I seek consensus.", function: "F", orientation: "extraverted" },
  { id: "fe-11", question: "I mediate interpersonal tension.", function: "F", orientation: "extraverted" },
  { id: "fe-12", question: "I track others’ emotional responses.", function: "F", orientation: "extraverted" },
  { id: "fe-13", question: "I respond to social cues automatically.", function: "F", orientation: "extraverted" },
  { id: "fe-14", question: "I consider collective values.", function: "F", orientation: "extraverted" },
  { id: "fe-15", question: "I feel attuned to relational dynamics.", function: "F", orientation: "extraverted" },
  { id: "fe-16", question: "I evaluate situations socially.", function: "F", orientation: "extraverted" }
];
