export const QUESTIONS = [
  "You try to help people to the point where you begin to forget taking care of your own needs.",
  "You stay true to yourself.",
  "You are a risk-taker.",
  "You frequently have hunches or insights about the future that turn out to be correct.",
  "You have an eye for aesthetics and \u201cenjoy the finer things in life.\u201d",
  "You become upset when your care for others goes unappreciated.",
  "You cannot help but get hung up on small details.",
  "You may be described as ditzy or scatterbrained.",
  "You often arrive at conclusions that seem to come out of nowhere; you relate to \u201crealizing\u201d answers.",
  "You may be seen as reckless and unknowingly hurt those around you.",
  "You relate present experiences back to past experiences.",
  "You work through problems by yourself and detach yourself from other people to arrive at a conclusion.",
  "You find yourself agreeing with those who claim that the ends justify the means.",
  "You are often the first to react to a question.",
  "You see so many possibilities that you have trouble committing to a single one.",
  "You consider yourself an organized person and take control of situations before they get out of hand.",
  "You consider yourself a practical and realistic person, free from imagination.",
  "You place a great amount of trust in the mysterious and unconscious world.",
  "You become upset when your care for others goes unappreciated.",
  "You would do whatever it takes to win a debate.",
  "You have been consistently logical throughout your life.",
  "You may be seen as reckless and unknowingly hurt those around you.",
  "You have an uncanny ability of recognizing others\u2019 needs.",
  "You easily recognize internal bodily sensations and act to suit your body\u2019s needs.",
  "You often feel awkward and aimless during leisure time.",
  "You value inclusion and try your best to involve everyone in a group.",
  "You have a strict internal moral code that comes from within regardless of any external standards.",
  "You express yourself honestly and authentically.",
  "You constantly set yourself on goals and objectives.",
  "You often use analogies and similes to communicate new ideas.",
  "You feel as though you are one of the only truly nice people left in this world.",
  "You place a lot of value on details and past experiences.",
  "You are skilled at recognizing whether the details in front of you match what you are used to.",
  "You find it difficult to concentrate on a single subject.",
  "You have an excellent sense of direction and instantly know your way around a new place.",
  "You trust hard facts and data more than anything else.",
  "You are able to manipulate conversations by reading others\u2019 body language.",
  "Fake people bother you.",
  "You easily sympathize with others\u2019 struggles.",
  "You believe that arriving at a truth is more important than winning an argument.",
  "You understand a concept by logically recognizing and drawing patterns between different, already known concepts.",
  "You modify internal logical frameworks to account for new data, and you sometimes find yourself re-evaluating them when new data is incompatible with it.",
  "Generally, you would prefer a solution be thorough before putting it into action (at the cost of time).",
  "You start many different projects, but you finish few.",
  "You tend to express sympathy only after you empathize with someone.",
  "You are drawn toward the abstract and often obsess over meanings.",
  "You believe your presence is greatly felt in a room.",
  "You are described as \u201cstuck in your ways.\u201d",
  "You are fiercely individualistic and pride yourself on your uniqueness.",
  "You live in the \u201chere and now.\u201d",
  "You explore things in depth for purely for the sake of exploring them in depth.",
  "You thrive on new and exciting experiences.",
  "You imagine things that aren\u2019t directly connected to the real world.",
  "You are aware of your surroundings and aren\u2019t likely to miss something right in front of you.",
  "You often arrive at conclusions that seem to come out of nowhere; you relate to \u201crealizing\u201d answers.",
  "You stay true to yourself.",
  "You sometimes fail to adapt to new data because it is not consistent with your personal understanding of an idea.",
  "You can easily think of something random to say.",
  "You have an eye for aesthetics and \u201cenjoy the finer things in life.\u201d",
  "You see the world as a bundle of possibilities waiting to be explored.",
  "You would rather sugarcoat a problem than upset someone.",
  "You are hesitant to strictly conform to social roles.",
  "You feel a strong sense of unity when communicating with others in a group.",
  "You are unnerved by uncertainty and the unknown.",
  "You have trouble communicating with those who do not think like you.",
  "You follow a consistent routine.",
  "You feel as though your insights often go misunderstood.",
  "You are attracted to symbolism, mysticism and the unknown.",
  "You cannot help but get hung up on small details.",
  "You have trouble communicating your ideas with people.",
  "You have a tendency to go off-topic in conversation.",
  "You take on subjects with a burning interest only to drop them once they no longer feel new to you.",
  "You come up with internal logical frameworks, theories, and systems to describe the world around you.",
  "You are drawn to the new, novel, and original.",
  "You like to organize things for pleasure.",
  "You become stubborn and resolute in the face of opposition when it comes to your personal beliefs.",
  "You greatly value social harmony and often go out of your way to maintain it.",
  "You prefer living in your dreams to living in the real world.",
  "You may be described as ditzy or scatterbrained.",
  "You absorb information from the outside world without additional processing.",
  "You have a strong tendency to see things as either good or bad.",
  "You value truth and logic more than anything else.",
  "You would question anything.",
  "You greatly value tradition and duty.",
  "You may be viewed as selfish or self-centered.",
  "You dislike change.",
  "You \u201cjust know\u201d things without being able to consciously put them into words.",
  "You streamline existing systems for the sake of efficiency and productivity.",
  "You frequently have hunches or insights about the future that turn out to be correct.",
  "You try to help people to the point where you begin to forget taking care of your own needs.",
  "You see the big picture in a sea of details.",
  "You rely only on past experiences to guide yourself through the present.",
  "You generally work through problems with others and involve yourself with other people to arrive at a conclusion.",
  "You live in the present, not the past or the future.",
  "You may be viewed as \u201cmeddling\u201d or \u201ccontrolling\u201d to others.",
  "You are an excellent problem solver and have an incredible ability to analyze things in depth."
];
